-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/OryKratos/sql/ory_kratos.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ory_kratos (
  kratos_user INT NOT NULL,
  kratos_id TEXT NOT NULL,
  kratos_host TEXT NOT NULL,
  PRIMARY KEY(kratos_user)
);

CREATE INDEX ory_kratos_id ON ory_kratos (kratos_id, kratos_host);
