-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/orykratos_equiv.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE orykratos_equiv (
  equiv_user INT NOT NULL,
  equiv_normalized TEXT NOT NULL,
  PRIMARY KEY(equiv_user)
);

CREATE INDEX orykratos_equiv_user_normalized ON orykratos_equiv (equiv_user, equiv_normalized);
