-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/orykratos.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE orykratos (
  kratos_user INT NOT NULL,
  kratos_identity TEXT NOT NULL,
  PRIMARY KEY(kratos_user)
);

CREATE INDEX orykratos_user_identity ON orykratos (kratos_user, kratos_identity);
