-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/orykratos.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/orykratos (
  kratos_user INTEGER UNSIGNED NOT NULL,
  kratos_identity BLOB NOT NULL,
  PRIMARY KEY(kratos_user)
);

CREATE INDEX orykratos_user_identity ON /*_*/orykratos (kratos_user, kratos_identity);
