-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/orykratos.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/orykratos (
  kratos_user INT UNSIGNED NOT NULL,
  kratos_identity VARBINARY(36) NOT NULL,
  INDEX orykratos_user_identity (kratos_user, kratos_identity),
  PRIMARY KEY(kratos_user)
) /*$wgDBTableOptions*/;
