-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/orykratos_equiv.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/orykratos_equiv (
  equiv_user INT UNSIGNED NOT NULL,
  equiv_normalized VARBINARY(255) NOT NULL,
  INDEX orykratos_equiv_user_normalized (equiv_user, equiv_normalized),
  PRIMARY KEY(equiv_user)
) /*$wgDBTableOptions*/;
